### ISSUE TITLE
Add "check for new prints" toggle

### ISSUE THREAD

**Issue by drewgates** [SparkMakerspace/3d-Printer-Web-receiver#5]
This would allow you to automatically pause *after* the current print.

**Comment by mmiscool** [comment]
I will be adding a setting that will optionally prompt the user to click ok before fetching new prints. This way the gcode sender can be used with printers that have no auto ejection capability. The user could crape the item off the print bed and hit ok when they are done. This would allow legacy printers to be managed the same way automatic ones are.

**Comment by mmiscool** [comment]
Added option to pop up a notice window after a print is finished.
This notice window requires  the user to click "OK" in order for the printer to attempt to fetch and start any print jobs.
